apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::497557220284:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-19KZUD55MJ0KY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::497557220284:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-02T02:48:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1401"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 3c7eb611-2866-40f8-ade8-9f918f4afe23
